// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjukvklnpqpiwbawihep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqdWt2a2xucHFwaXdiYXdpaGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjI2MjcsImV4cCI6MjA2MzUzODYyN30.IRz4tXePc_O1XornvfLvGlIquTY1bMyt54NwrfwU7ZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);